name: Check env.log Presence

on:
  push:
    branches:
      - master

jobs:
  check-env-log-file:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Python 3.10 setup
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Add a step to check for env.log in the root directory
      - name: Check for env.log file
        run: |
          if [ ! -f env.log ]; then
            echo "env.log file is missing in the root directory."
            exit 1
          else
            echo "env.log file found."
          fi