name: Check env.log Presence

# This workflow triggers on push events to the master branch.
on:
  push:
    branches:
      - master

jobs:
  check-env-log-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Check for env.log file
        run: |
          if [ ! -f env.log ]; then
            echo "env.log file is missing in the root directory."
            exit 1 # Causes the workflow to fail if env.log is not found
          else
            echo "env.log file found."
