# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string

jobs:
  check-file-existence:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository
        uses: actions/checkout@v2
        with:
          repository: amstokely/env_check
          ref: master
      - name: Execute Python script to check file existence
        run: python check.py "${{ inputs.file_path }}"
        env:
          FILE_PATH: ${{ inputs.file_path }}
